name: Build and Upload FNF Android Port

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2

      # Make Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Build the project
      - name: Build the project
        run: ./gradlew clean assembleRelease

      # Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-build
          path: app/build/outputs/apk/release/*.apk
